### PR TITLE
Fixed the autoloading when installing through composer

### PR DESCRIPTION
**Pull request by stof**
The repository structure does not match PSR-0 so it needs to use the classmap autoloading.

### CODE REVIEW

**Comment by wikimatze** [comment]
Hey, we run into the same problem today, would be nice to get the stable release.

**Comment by cweiske** [comment]
I've removed pear_exception since it's not used anyway. To get a stable release, we'd have to make a new release.

@quipo - could you do that?

**Comment by stof** [comment]
@cweiske the code is still doing require_once calls rather than relying on autoloading btw. Are you planning to change that ?

**Comment by cweiske** [comment]
It's required for pear compatibility, so it will stay in. We could do `class_exists` calls and if they fail use require_once, but that does not really improve things.

**Pull request closed without merging**
